name: Train Models

on:
  push:
    paths:
      - 'model/scripts/train.py' # Trigger workflow on changes to this file
      - 'model/sccripts/config.json'

jobs:
  train_models:
    name: Train Models on Change
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set Up Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r airflow-config/requirements.txt

    - name: Run Setup Script
      run: |
        chmod +x setup.sh
        ./setup.sh

    - name: Download Dataset using DVC
      run: |
        python dataset/scripts/dvc_manager.py download --save_local 1 --file_name data_preprocess.csv

    - name: Train Model with LSTM
      run: |
        python model/scripts/train.py dataset/data/data_preprocess.csv --config model/scripts/config.json --model lstm

    - name: Train Model with XGBoost
      run: |
        python model/scripts/train.py dataset/data/data_preprocess.csv --config model/scripts/config.json --model xgboost

    - name: Train Model with Logistic Regression
      run: |
        python model/scripts/train.py dataset/data/data_preprocess.csv --config model/scripts/config.json --model lr
